//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP.NETDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produits
    {
        public Produits()
        {
            this.Images = new HashSet<Images>();
        }
    
        public int id { get; set; }
        public string label { get; set; }
        public string description { get; set; }
        public int prix { get; set; }
    
        public virtual ICollection<Images> Images { get; set; }
    }
}
